apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: nexus-observability
  labels:
    app: opensearch
spec:
  type: LoadBalancer
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: http
    - name: metrics
      port: 9600
      targetPort: metrics
