apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-mcp
  namespace: nexus-mcp
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/nexus-dev-aws-mcp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-mcp
  namespace: nexus-mcp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-mcp
  namespace: nexus-mcp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-mcp
  namespace: nexus-mcp
