apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-simulator
  namespace: nexus-data
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/nexus-dev-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kinesis-opensearch
  namespace: nexus-data
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/nexus-dev-agent
